// @ts-nocheck
import React, {useEffect, useMemo, useState} from 'react';
import {createRoot} from 'react-dom/client';
import './style.css';

const API = import.meta.env.DEV ? 'http://localhost:8000' : '/api';
type Show = {id:number,title:string,slug:string,section:string,categories:string[],synopsis:string,artwork:Record<string,string>,episodes:any[]};
const placeholder = (title:string) => `linear-gradient(135deg, #${['8c3e9d','e56458','176b87','c7913e'][title.length%4]}, #17162c)`;

function useFetch<T>(url:string, token?:string) {
  const [data,setData]=useState<T|null>(null), [error,setError]=useState(''), [version,setVersion]=useState(0);
  useEffect(()=>{let active=true; setData(null); setError(''); fetch(API+url,{headers:token?{Authorization:`Bearer ${token}`}:{}}).then(r=>r.ok?r.json():r.json().then(x=>Promise.reject(x.detail||'Request failed'))).then(x=>active&&setData(x)).catch(x=>active&&setError(typeof x==='string'?x:JSON.stringify(x))); return()=>{active=false}},[url,token,version]);
  return {data,error,refetch:()=>setVersion(x=>x+1)};
}

function ArtworkImage({path,title,className}:{path?:string,title:string,className?:string}) {
  const [failed,setFailed]=useState(false),[loaded,setLoaded]=useState(false);
  useEffect(()=>{setFailed(false);setLoaded(false)},[path]);
  return <div className={`artwork ${className||''} ${loaded?'loaded':''}`} style={{background:placeholder(title)}}>{path&&!failed&&<img src={API+path} alt="" onLoad={()=>setLoaded(true)} onError={()=>setFailed(true)}/>} {!loaded&&!failed&&path&&<span className="image-skeleton"/>}</div>;
}

function App(){const [mode,setMode]=useState<'viewer'|'cms'>('viewer'); return <><nav><div className="brand">peblo<span>tv</span></div><button className={mode==='viewer'?'active':''} onClick={()=>setMode('viewer')}>Browse</button><button className={mode==='cms'?'active':''} onClick={()=>setMode('cms')}>CMS</button></nav>{mode==='viewer'?<Viewer/>:<CMS/>}</>}

function Viewer(){
 const {data,error}=useFetch<any>('/catalog'); const [query,setQuery]=useState(''),[category,setCategory]=useState(''),[language,setLanguage]=useState(''),[selected,setSelected]=useState<Show|null>(null);
 const shows=useMemo(()=>data?.sections.flatMap((r:any)=>r.shows)||[],[data]); const filtered=shows.filter((s:Show)=>!query||`${s.title} ${s.categories.join(' ')} ${s.episodes.map(e=>e.title).join(' ')}`.toLowerCase().includes(query.toLowerCase())).filter((s:Show)=>!category||s.categories.includes(category)).map((s:Show)=>({...s,episodes:!language?s.episodes:s.episodes.filter(e=>e.languages.includes(language))})).filter((s:Show)=>s.episodes.length);
 if(error)return <main className="state">Could not load the published catalogue: {error}</main>; if(!data)return <main className="state">Loading Peblo TV…</main>; if(selected)return <Detail show={selected} back={()=>setSelected(null)}/>; const hero=shows[0]; if(!hero)return <main className="state">No published shows yet.</main>;
 return <main><section className="hero"><ArtworkImage path={hero.artwork?.banner} title={hero.title} className="hero-art"/><div className="scrim"><p className="eyebrow">FEATURED ADVENTURE</p><h1>{hero.title}</h1><p>{hero.synopsis}</p><button onClick={()=>setSelected(hero)}>Explore show</button></div></section><div className="filters"><input placeholder="Search shows and episodes" value={query} onChange={e=>setQuery(e.target.value)}/><select value={category} onChange={e=>setCategory(e.target.value)}><option value="">All categories</option>{[...new Set(shows.flatMap((s:Show)=>s.categories))].sort().map(x=><option key={x}>{x}</option>)}</select><select value={language} onChange={e=>setLanguage(e.target.value)}><option value="">All languages</option><option value="en">English</option><option value="hi">Hindi</option></select></div>{data.sections.map((row:any)=><section className="row" key={row.name}><h2>{row.name}</h2><div className="cards">{filtered.filter((s:Show)=>s.section===row.name).map((s:Show)=><button className="card" key={s.id} onClick={()=>setSelected(s)}><ArtworkImage path={s.artwork?.poster} title={s.title} className="cover"/><strong>{s.title}</strong><small>{s.episodes.length} episodes</small></button>)}</div></section>)}{!filtered.length&&<div className="state">No shows match those filters. Try a different search.</div>}</main>;
}

function Detail({show,back}:{show:Show,back:()=>void}){const seasons=[...new Set(show.episodes.filter(e=>e.season_number>0).map(e=>e.season_number))];return <main className="detail"><button className="back" onClick={back}>← Back to browse</button><section className="detail-head"><ArtworkImage path={show.artwork?.banner} title={show.title} className="detail-art"/><div className="detail-copy"><h1>{show.title}</h1><p>{show.synopsis}</p><div>{show.categories.map(x=><span className="tag" key={x}>{x}</span>)}</div></div></section>{seasons.map(season=><section key={season}><h2>Season {season}</h2>{show.episodes.filter(e=>e.season_number===season).map(e=><article className="episode" key={e.content_group}><ArtworkImage path={show.artwork?.thumbnail} title={show.title} className="thumb"/><div><strong>{e.episode_number}. {e.title}</strong><p>{Math.round(e.duration_seconds/60)} min · {e.languages.map((l:string)=>l==='en'?'English':'Hindi').join(' / ')}</p></div></article>)}</section>)}<p className="trailer-note">Trailers are available separately and are not included in seasons.</p></main>}

function CMS(){
 const [token,setToken]=useState('admin-demo'),[q,setQ]=useState(''),[section,setSection]=useState(''),[status,setStatus]=useState(''),[language,setLanguage]=useState(''),[page,setPage]=useState(1),[message,setMessage]=useState('');
 const query=new URLSearchParams(Object.entries({q,section,status,language,page:String(page),page_size:'10'}).filter(([,v])=>v)).toString();
 const {data:shows,error,refetch:refreshShows}=useFetch<any>(`/admin/shows?${query}`,token); const {data:report,refetch:refreshReport}=useFetch<any>('/admin/validation-report',token); const {data:runs,refetch:refreshRuns}=useFetch<any>('/admin/publish-runs',token);
 const refresh=()=>{refreshShows();refreshReport();refreshRuns()}; const save=async(path:string,payload:object)=>{const r=await fetch(API+path,{method:'PUT',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify(payload)}); if(!r.ok)setMessage((await r.json()).detail||'Save failed'); else {setMessage('Saved.');refresh()}};
 const dismiss=async(id:number)=>{const r=await fetch(`${API}/admin/import-issues/${id}`,{method:'DELETE',headers:{Authorization:`Bearer ${token}`}});setMessage(r.ok?'Issue dismissed.':(await r.json()).detail||'Could not dismiss issue.');refresh()};
 const publish=async()=>{const r=await fetch(API+'/admin/catalog/publish',{method:'POST',headers:{Authorization:`Bearer ${token}`}});setMessage(r.ok?'Catalogue published atomically. Refresh Browse to see it.':(await r.json()).detail?.message||'Publishing is blocked — resolve the issues below.');refreshRuns()};
 const loading=!shows||!report||!runs;
 return <main className="cms"><header><div><p className="eyebrow">INTERNAL CONTENT STUDIO</p><h1>Catalogue CMS</h1></div><label>Role token<select value={token} onChange={e=>setToken(e.target.value)}><option value="admin-demo">Admin</option><option value="editor-demo">Editor</option></select></label></header>{loading?<div className="panel state">Loading catalogue workspace…</div>:error?<div className="error">{error}</div>:<><section className="publish"><div><h2>Ready to publish?</h2><p>{report.blocked?`${report.issue_count} issue${report.issue_count===1?'':'s'} need attention.`:'Everything meets the publishing rules.'}</p></div><button disabled={report.blocked||token!=='admin-demo'} onClick={publish}>Publish catalogue</button></section>{message&&<p className="notice">{message}</p>}<section className="panel"><h2>Validation report</h2>{report.issues?.length?<ul>{report.issues.map((x:any,i:number)=><li key={i}><b>{x.type.replace('_',' ')}</b> — {x.message} {x.id&&<button className="small-button" onClick={()=>dismiss(x.id)}>Dismiss</button>}</li>)}</ul>:<p>No blockers. Your catalogue is publishable.</p>}</section><section className="panel"><h2>Shows</h2><div className="cms-filters"><input placeholder="Search shows" value={q} onChange={e=>{setQ(e.target.value);setPage(1)}}/><select value={section} onChange={e=>{setSection(e.target.value);setPage(1)}}><option value="">All sections</option><option value="series">Series</option><option value="movies">Movies</option><option value="kids">Kids</option></select><select value={status} onChange={e=>{setStatus(e.target.value);setPage(1)}}><option value="">All statuses</option><option value="draft">Draft</option><option value="published">Published</option></select><select value={language} onChange={e=>{setLanguage(e.target.value);setPage(1)}}><option value="">All languages</option><option value="en">English</option><option value="hi">Hindi</option></select></div><div className="table">{shows.items.map((s:any)=><ShowRow key={s.id} show={s} token={token} save={save} refresh={refresh}/>)}</div><div className="pagination"><button disabled={page<=1} onClick={()=>setPage(page-1)}>Previous</button><span>Page {page} · {shows.total} shows</span><button disabled={page*10>=shows.total} onClick={()=>setPage(page+1)}>Next</button></div></section><section className="panel"><h2>Publish history</h2>{runs.length?runs.map((r:any)=><p key={r.id}>{new Date(r.created_at).toLocaleString()} · <b>{r.outcome}</b> · {r.show_count} shows / {r.episode_count} grouped episodes</p>):<p>No publish attempts yet.</p>}</section></>}</main>;
}

function ShowRow({show,token,save,refresh}:{show:any,token:string,save:any,refresh:any}){const [open,setOpen]=useState(false);return <div className="show-row"><div className="show-summary"><ArtworkImage path={show.artwork?.poster} title={show.title} className="mini-cover"/><strong>{show.title}</strong><select value={show.section||''} onChange={e=>save(`/admin/shows/${show.id}`,{section:e.target.value||null})}><option value="">No section</option><option value="series">Series</option><option value="movies">Movies</option><option value="kids">Kids</option></select><select value={show.status} onChange={e=>save(`/admin/shows/${show.id}`,{status:e.target.value})}><option value="draft">Draft</option><option value="published">Published</option></select><span>{show.episodes} episodes</span><button className="small-button" onClick={()=>setOpen(!open)}>{open?'Hide episodes':'Edit episodes'}</button><Artwork show={show} token={token} refresh={refresh}/></div>{open&&<div className="episode-editor">{show.episode_items.map((ep:any)=><div key={ep.id}><span>S{ep.season_number} E{ep.episode_number}: {ep.title}</span><label>Duration<input type="number" defaultValue={ep.duration_seconds??''} onBlur={e=>save(`/admin/episodes/${ep.id}`,{duration_seconds:Number(e.target.value)||null})}/></label><label>Language<select defaultValue={ep.language} onChange={e=>save(`/admin/episodes/${ep.id}`,{language:e.target.value})}><option value="en">English</option><option value="hi">Hindi</option></select></label></div>)}</div>}</div>}

function Artwork({show,token,refresh}:{show:any,token:string,refresh:any}){const [note,setNote]=useState(''),[previews,setPreviews]=useState<Record<string,string>>({});const upload=async(kind:string,file:File)=>{const preview=URL.createObjectURL(file);setPreviews(x=>({...x,[kind]:preview}));const f=new FormData();f.append('file',file);const r=await fetch(`${API}/admin/shows/${show.id}/artwork/${kind}`,{method:'POST',headers:{Authorization:`Bearer ${token}`},body:f});setNote(r.ok?`${kind} uploaded`:(await r.json()).detail);if(r.ok)refresh()};return <div className="upload">{['poster','banner','thumbnail'].map(k=><label key={k}>{previews[k]&&<img className="upload-preview" src={previews[k]} alt={`${k} preview`}/>} {k}<small>{k==='poster'?'600×900':'16:9'} · 200 KB max</small><input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>e.target.files?.[0]&&upload(k,e.target.files[0])}/></label>)}{note&&<em>{note}</em>}</div>}

createRoot(document.getElementById('root')!).render(<App/>);
