// @ts-nocheck
import React, {useEffect, useMemo, useState} from 'react';
import {createRoot} from 'react-dom/client';
import './style.css';

const API = import.meta.env.DEV ? 'http://localhost:8000' : '/api';
type Show = {id:number,title:string,slug:string,section:string,categories:string[],synopsis:string,artwork:Record<string,string>,episodes:any[]};
const placeholder = (title:string, wide=false) => `linear-gradient(135deg, #${['8c3e9d','e56458','176b87','c7913e'][title.length%4]}, #17162c)`;
function useFetch<T>(url:string, token?:string) { const [data,setData]=useState<T|null>(null); const [error,setError]=useState(''); useEffect(()=>{fetch(API+url,{headers:token?{Authorization:`Bearer ${token}`}:{}}).then(r=>r.ok?r.json():r.json().then(x=>Promise.reject(x.detail||'Request failed'))).then(setData).catch(x=>setError(typeof x==='string'?x:JSON.stringify(x)))},[url,token]); return {data,error}; }
function App(){const [mode,setMode]=useState<'viewer'|'cms'>('viewer'); return <><nav><div className="brand">peblo<span>tv</span></div><button className={mode==='viewer'?'active':''} onClick={()=>setMode('viewer')}>Browse</button><button className={mode==='cms'?'active':''} onClick={()=>setMode('cms')}>CMS</button></nav>{mode==='viewer'?<Viewer/>:<CMS/>}</>}
function Viewer(){const {data,error}=useFetch<any>('/catalog'); const [query,setQuery]=useState(''); const [category,setCategory]=useState(''); const [language,setLanguage]=useState(''); const [selected,setSelected]=useState<Show|null>(null);
 const shows=useMemo(()=>data?.sections.flatMap((r:any)=>r.shows) || [],[data]); const filtered=shows.filter((s:Show)=>!query||`${s.title} ${s.categories.join(' ')} ${s.episodes.map(e=>e.title).join(' ')}`.toLowerCase().includes(query.toLowerCase())).filter((s:Show)=>!category||s.categories.includes(category)).map((s:Show)=>({...s,episodes:!language?s.episodes:s.episodes.filter(e=>e.languages.includes(language))})).filter((s:Show)=>s.episodes.length);
 if(error)return <main className="state">Could not load the published catalogue: {error}</main>; if(!data)return <main className="state">Loading Peblo TV…</main>; if(selected)return <Detail show={selected} back={()=>setSelected(null)}/>;
 const hero=shows[0]; return <main><section className="hero" style={{background:placeholder(hero.title,true)}}><div className="scrim"><p className="eyebrow">FEATURED ADVENTURE</p><h1>{hero.title}</h1><p>{hero.synopsis}</p><button onClick={()=>setSelected(hero)}>Explore show</button></div></section><div className="filters"><input placeholder="Search shows and episodes" value={query} onChange={e=>setQuery(e.target.value)}/><select value={category} onChange={e=>setCategory(e.target.value)}><option value="">All categories</option>{[...new Set(shows.flatMap((s:Show)=>s.categories))].sort().map(x=><option key={x}>{x}</option>)}</select><select value={language} onChange={e=>setLanguage(e.target.value)}><option value="">All languages</option><option value="en">English</option><option value="hi">Hindi</option></select></div>{data.sections.map((row:any)=><section className="row" key={row.name}><h2>{row.name}</h2><div className="cards">{filtered.filter((s:Show)=>s.section===row.name).map((s:Show)=><button className="card" key={s.id} onClick={()=>setSelected(s)}><div className="cover" style={{background:placeholder(s.title)}}><span>{s.categories[0]}</span></div><strong>{s.title}</strong><small>{s.episodes.length} episodes</small></button>)}</div></section>)}{!filtered.length&&<div className="state">No shows match those filters. Try a different search.</div>}</main>}
function Detail({show,back}:{show:Show,back:()=>void}){const seasons=[...new Set(show.episodes.filter(e=>e.season_number>0).map(e=>e.season_number))];return <main className="detail"><button className="back" onClick={back}>← Back to browse</button><section className="detail-head" style={{background:placeholder(show.title,true)}}><h1>{show.title}</h1><p>{show.synopsis}</p><div>{show.categories.map(x=><span className="tag" key={x}>{x}</span>)}</div></section>{seasons.map(season=><section key={season}><h2>Season {season}</h2>{show.episodes.filter(e=>e.season_number===season).map(e=><article className="episode" key={e.content_group}><div className="thumb"/><div><strong>{e.episode_number}. {e.title}</strong><p>{Math.round(e.duration_seconds/60)} min · {e.languages.map((l:string)=>l==='en'?'English':'Hindi').join(' / ')}</p></div></article>)}</section>)}<p className="trailer-note">Trailers are available separately and are not included in seasons.</p></main>}
function CMS(){const [token,setToken]=useState('admin-demo'); const {data:shows,error}=useFetch<any>('/admin/shows',token); const {data:report}=useFetch<any>('/admin/validation-report',token); const {data:runs}=useFetch<any>('/admin/publish-runs',token); const [message,setMessage]=useState(''); const publish=async()=>{const r=await fetch(API+'/admin/catalog/publish',{method:'POST',headers:{Authorization:`Bearer ${token}`}});setMessage(r.ok?'Catalogue published atomically. Refresh Browse to see it.':(await r.json()).detail?.message||'Publishing is blocked — resolve the issues below.');};return <main className="cms"><header><div><p className="eyebrow">INTERNAL CONTENT STUDIO</p><h1>Catalogue CMS</h1></div><label>Role token<select value={token} onChange={e=>setToken(e.target.value)}><option value="admin-demo">Admin</option><option value="editor-demo">Editor</option></select></label></header>{error?<div className="error">{error}</div>:<><section className="publish"><div><h2>Ready to publish?</h2><p>{report?.blocked?`${report.issue_count} issue${report.issue_count===1?'':'s'} need attention.`:'Everything meets the publishing rules.'}</p></div><button disabled={report?.blocked||token!=='admin-demo'} onClick={publish}>Publish catalogue</button></section>{message&&<p className="notice">{message}</p>}<section className="panel"><h2>Validation report</h2>{report?.issues?.length?<ul>{report.issues.map((x:any,i:number)=><li key={i}><b>{x.type.replace('_',' ')}</b> — {x.message}</li>)}</ul>:<p>No blockers. Your catalogue is publishable.</p>}</section><section className="panel"><h2>Shows</h2><div className="table">{shows?.items?.map((s:any)=><div key={s.id}><div className="mini-cover" style={{background:placeholder(s.title)}}/><strong>{s.title}</strong><span>{s.section||'No section'}</span><span>{s.status}</span><span>{s.episodes} episodes</span><Artwork show={s} token={token}/></div>)}</div></section><section className="panel"><h2>Publish history</h2>{runs?.length?runs.map((r:any)=><p key={r.id}>{new Date(r.created_at).toLocaleString()} · <b>{r.outcome}</b> · {r.show_count} shows / {r.episode_count} grouped episodes</p>):<p>No publish attempts yet.</p>}</section></>}</main>}
function Artwork({show,token}:{show:any,token:string}){const [note,setNote]=useState('');const upload=async(kind:string,file:File)=>{const f=new FormData();f.append('file',file);const r=await fetch(`${API}/admin/shows/${show.id}/artwork/${kind}`,{method:'POST',headers:{Authorization:`Bearer ${token}`},body:f});setNote(r.ok?`${kind} uploaded`:(await r.json()).detail)};return <div className="upload">{['poster','banner','thumbnail'].map(k=><label key={k}>{k}<small>{k==='poster'?'600×900':'16:9'} · 200 KB max</small><input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>e.target.files?.[0]&&upload(k,e.target.files[0])}/></label>)}{note&&<em>{note}</em>}</div>}
createRoot(document.getElementById('root')!).render(<App/>);
